/**
 * AppStorage 键名常量
 */

export class StorageKeys {
  static GLOBAL_DROP_HANDLED: string = 'GLOBAL_DROP_HANDLED'
  static CARD_ITEM_LEVEL_MAP: string = 'CARD_ITEM_LEVEL_MAP'
  static LEVEL_STAT_UPDATE: string = 'LEVEL_STAT_UPDATE'
  static LEVEL_STAT_REMOVE: string = 'LEVEL_STAT_REMOVE'
  static LEVEL_STAT_UPDATE_BATCH: string = 'LEVEL_STAT_UPDATE_BATCH'
  static REMOVE_SOURCE_DATA: string = 'REMOVE_SOURCE_DATA'
  static FORCE_REMOVE_SOURCE: string = 'FORCE_REMOVE_SOURCE'
}


