export namespace OmniFilterConstants{
  export declare const OMNI_FILTER_LIST_DEEP_SELECT_BG = 0xFFF8F8F8
  export declare const OMNI_FILTER_LIST_MIDDLE_SELECT_BG = 0xFFFFFFFF
  export declare const OMNI_FILTER_LIST_LIGHT_SELECT_BG = 0xFFFFFFFF

  export declare const OMNI_FILTER_LIST_DEEP_NORMAL_BG = 0xFFF0F0F0
  export declare const OMNI_FILTER_LIST_MIDDLE_NORMAL_BG = 0xFFF8F8F8
  export declare const OMNI_FILTER_LIST_LIGHT_NORMAL_BG = 0xFFFFFFFF
}
